sim/mahasiswa/routes.py
from flask import Flask, render_template, redirect, url_for, Blueprint, flash, request
from sim.mahasiswa.forms import mahasiswa_F, loginmahasiswa_F, editmahasiswa_F, pengaduan_F,editpengaduan_F,pendataan_F, editpendataan_F
from sim.models import Tmahasiswa, Tpengaduan,Tpendataan
from sim import db, bcrypt
from flask_login import login_user, current_user, logout_user, login_required
import os
import secrets
from sim import app
from PIL import Image

rmahasiswa= Blueprint('rmahasiswa',__name__)

@rmahasiswa.route("/")
def home():
    return render_template("home.html")

@rmahasiswa.route ("/about")
def about():
    return render_template("about.html")

@rmahasiswa.route ("/data_mahasiswa", methods=['GET', 'POST'])
def data_m():
    form=mahasiswa_F()
    if form.validate_on_submit():
        pass_hash=bcrypt.generate_password_hash(form.password.data).decode('UTF-8')
        add_mahasiswa=Tmahasiswa(npm=form.npm.data, nama=form.nama.data, email=form.email.data,
        password=pass_hash, kelas=form.kelas.data, alamat=form.alamat.data)
        db.session.add(add_mahasiswa)
        db.session.commit()
        flash(f'Akun- {form.npm.data} berhasil daftar','info')
        return redirect(url_for('rmahasiswa.login_mahasiswa'))
    return render_template("data-mahasiswa.html", form=form)

    
@rmahasiswa.route ("/login_mahasiswa", methods=['GET', 'POST'])
def login_mahasiswa():
    if current_user.is_authenticated:
        return redirect(url_for('rmahasiswa.home'))
    form=loginmahasiswa_F()
    if form.validate_on_submit():
        ceknpm= Tmahasiswa.query.filter_by(npm=form.npm.data).first()
        if ceknpm and bcrypt.check_password_hash(ceknpm.password, form.password.data):
            login_user(ceknpm)
            flash('Selamat Datang Kembali', 'warning')
            return redirect(url_for('rmahasiswa.akunmahasiswa'))
        else:
            flash('Login Gagal, Periksa NPM dan Password Kembali!', 'danger')
    return render_template("login_mahasiswa.html", form=form)

@rmahasiswa.route ("/akunmahasiswa")
def akunmahasiswa():
    return render_template('akunmahasiswa.html')


@rmahasiswa.route ("/logout_mahasiswa")
def logout_mahasiswa():
    logout_user()
    return redirect(url_for('rmahasiswa.home'))



#simpan foto
def simpan_foto(form_foto):
    random_hex= secrets.token_hex(8)
    f_name, f_ext= os.path.splitext(form_foto.filename)
    foto_fn= random_hex + f_ext
    foto_path= os.path.join(app.root_path, 'sim/static/foto', foto_fn)
    ubah_size=(300,300)
    j=Image.open(form_foto)
    j.thumbnail(ubah_size)
    j.save(foto_path)
    #form_foto.save(foto_path)
    return foto_fn 

@rmahasiswa.route ("/edit_mahasiswa", methods=['GET', 'POST'])
@login_required
def edit_mahasiswa():
    form=editmahasiswa_F()
    if form.validate_on_submit():
        if form.foto.data:
            file_foto=simpan_foto(form.foto.data)
            current_user.foto = file_foto
        pass_hash=bcrypt.generate_password_hash(form.password.data).decode('UTF-8')  
        current_user.npm=form.npm.data
        current_user.nama=form.nama.data
        current_user.email=form.email.data
        current_user.kelas=form.kelas.data
        current_user.alamat=form.alamat.data
        current_user.password=pass_hash
        db.session.commit()
        flash('Data berhasil di Ubah', 'warning')
        return redirect(url_for('rmahasiswa.edit_mahasiswa'))
    elif request.method=="GET":
        form.npm.data=current_user.npm
        form.nama.data=current_user.nama
        form.email.data=current_user.email
        form.kelas.data=current_user.kelas
        form.alamat.data=current_user.alamat
    return render_template('edit_mahasiswa.html', form=form)


@rmahasiswa.route ("/pengaduan", methods=['GET', 'POST'])
@login_required
def pengaduan():
    dt_pengaduan=Tpengaduan.query.filter_by(mahasiswa_id=current_user.id)
    form=pengaduan_F()
    if form.validate_on_submit():
        #tambah data pengaduan
        add_pengaduan= Tpengaduan(subjek=form.subjek.data, kategori=form.kategori.data, detail_pengaduan=form.detail_pengaduan.data, mahasiswa=current_user)
        db.session.add(add_pengaduan)
        db.session.commit()
        flash('Data berhasil ditambahkan', 'warning')
        return redirect(url_for('rmahasiswa.pengaduan'))
    return render_template('pengaduan.html', form=form, dt_pengaduan=dt_pengaduan)

@rmahasiswa.route ("/pengaduan/<int:ed_id>/update", methods=['GET', 'POST'])
@login_required
def update_pengaduan(ed_id):
    form=editpengaduan_F()
    dt_pengaduan=Tpengaduan.query.get_or_404(ed_id)
    if request.method=="GET":
        form.subjek.data=dt_pengaduan.subjek
        form.kategori.data=dt_pengaduan.kategori
        form.detail_pengaduan.data=dt_pengaduan.detail_pengaduan
    elif form.validate_on_submit():
        dt_pengaduan.subjek=form.subjek.data
        dt_pengaduan.kategori=form.kategori.data
        dt_pengaduan.detail_pengaduan=form.detail_pengaduan.data
        db.session.commit()
        flash('Data Berhasil Diedit','warning')
        return redirect(url_for('rmahasiswa.pengaduan'))
        
    return render_template('edit_pengaduan.html',form=form)


@rmahasiswa.route ("/delete/<id>", methods=['GET', 'POST'])
@login_required
def hapus_pengaduan(id):
    h_pengaduan=Tpengaduan.query.get(id)
    db.session.delete(h_pengaduan)
    db.session.commit()
    flash('Data Berhasil Dihapus','warning')
    return redirect(url_for('rmahasiswa.pengaduan'))

@rmahasiswa.route ("/pengaduan/<int:ed_id>/detail", methods=['GET', 'POST'])
@login_required
def detail_pengaduan(ed_id):
    dt_pengaduan=Tpengaduan.query.get_or_404(ed_id)
    return render_template('detail_pengaduan.html',dt_pengaduan=dt_pengaduan)

@rmahasiswa.route ("/artikel/<info>")
def artikel_info(info):
    return "halaman artikel " + info ;



@rmahasiswa.route ("/pendataan", methods=['GET', 'POST'])
@login_required
def pendataanto():
    pendataan=Tpendataan.query.all()
    form=pendataan_F()
    if form.validate_on_submit():
        #tambah data pengaduan
        add_pendataan = Tpendataan(frekuensi=form.frekuensi.data, subjek=form.subjek.data, detail=form.detail.data)
        db.session.add(add_pendataan)
        db.session.commit()
        flash('Silahkan Lihat', 'warning')
        return redirect(url_for('rmahasiswa.pendataanto'))
    return render_template('pendataan.html', form=form, dt_pendataan=pendataan)

@rmahasiswa.route ("/pendataan/<int:ed_id>/update", methods=['GET', 'POST'])
@login_required
def update_pendataan(ed_id):
    form=editpendataan_F()
    dt_pengaduan=Tpendataan.query.get_or_404(ed_id)
    if request.method=="GET":
        form.subjek.data=dt_pengaduan.subjek
        form.frekuensi.data=dt_pengaduan.frekuensi
        form.detail.data=dt_pengaduan.detail
    elif form.validate_on_submit():
        dt_pengaduan.subjek=form.subjek.data
        dt_pengaduan.frekuensi=form.frekuensi.data
        dt_pengaduan.detail=form.detail.data
        db.session.commit()
        flash('Data Berhasil Diedit','warning')
        return redirect(url_for('rmahasiswa.pendataanto'))
        
    return render_template('edit_pendataan.html',form=form)

@rmahasiswa.route ("/pendataan/<int:ed_id>/detail", methods=['GET', 'POST'])
@login_required
def detail_pendataan(ed_id):
    dt_pendataan=Tpendataan.query.get_or_404(ed_id)
    return render_template('detail_pendataan.html',dt_pendataan=dt_pendataan)

@rmahasiswa.route ("/delete_pendataan/<id>", methods=['GET', 'POST'])
@login_required
def hapus_pendataan(id):
    h_pendataan=Tpendataan.query.get(id)
    db.session.delete(h_pendataan)
    db.session.commit()
    flash('Data Berhasil Dihapus','warning')
    return redirect(url_for('rmahasiswa.pendataanto'))

sim/templates/about.html
{% extends "base.html"%}

{% block konten%}

<h1>Tentang Kami</h1>
<br>
<p>Halaman ini berisi informasi tentang kami para MAHASIKSA yang sedang belajar membuat website menggunakan python.</p>
<br>
<P>Jdi guys PYTHON merupakan bahasa pemograman berorientasi objek(berbasis data)tingkat tinggi(lebih mudah di pahami oleh manusia).
    Pertama kali di luncurkan pada tahun 1992,Python dibuat dengan cara yang relatif intuitif untuk ditulis dan dipahami. Dengan demikian,
    Python merupakan bahasa coding yang ideal bagi mereka yang mengiginkan perkembangan pesat.
</P>

{% endblock%}

sim/templates/akunmahasiswa.html
{% extends "base.html"%}

{% block konten%}

<div class="jumbotron">
    
    <h1 class="display-4">Welcome, {{current_user.nama}}!</h1>
    <p class="lead">Selamat Datang di Sistem Informasi Pengaduan. Semoga segala pengaduan anda menjadi perbaikan kami</p>
    <hr class="my-4">
    <p>Klik untuk memulai pengaduan anda</p>
    <a class="btn btn-warning btn-lg" href="{{ url_for('rmahasiswa.pengaduan')}}" role="button">Pengaduan</a>
</div>

{% endblock%}

sim/templates/base.html
<html>

<head>
    <title>Selamat Datang</title>
    <!-- CSS only -->
    <link href="{{ url_for('static',filename='css/bootstrap.min.css')}}" rel="stylesheet"
        integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for ('static', filename= 'css/style.css')}}">

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-warning">

        <div class="container">
            <a class="navbar-brand" href="#">SIM PENGADUAN</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ url_for('rmahasiswa.home')}}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{{ url_for('rmahasiswa.about')}}">About</a>
                    </li>
                    {% if current_user.is_authenticated %}
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link active" href="{{url_for('rmahasiswa.login_mahasiswa')}}">Login Mahasiswa</a>
                    </li>
                    {% endif %}

                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active" href="{{url_for('rmahasiswa.pendataanto')}}">AGENDA DAN INFORMASI</a>
                    </li>
                    {% else %}
                    {% endif %}

                </ul>
                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>

    </nav>

    <div class="container mt-4">
        <div class="row">
            <div class="col-md-8">
                <div class="shadow p-3 mb-5 bg-white rounded">
                    <!--falsh-->
                    {% with messages= get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                    {% for category,massage in messages %}

                    <div class="alert alert-{{category}}">
                        {{massage}}
                    </div>
                    {% endfor %}
                    {% endif %}
                    {% endwith %}

                    {% block konten %}

                    {% endblock%}

                    
                </div>
            </div>

            <div class="col-md-4">
                <div class="shadow p-3 mb-5 bg-white rounded">

                    {% if current_user.is_authenticated %}
                    <div class="card" style="width: 20rem;">
                        <img src="{{url_for('static', filename='foto/' + current_user.foto)}}" class="card-img-top"
                            alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{current_user.nama}}</h5>
                            <p class="card-text">{{current_user.email}}</p>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item"> <a
                                    href="{{ url_for('rmahasiswa.akunmahasiswa')}}">Dashboard</a>
                            </li>
                            <li class="list-group-item"><a href="{{ url_for('rmahasiswa.pengaduan')}}">Pengaduan</a>
                            </li>

                            <li class="list-group-item">Vestibulum at eros</li>
                        </ul>
                        <div class="card-body">
                            <a href="{{ url_for('rmahasiswa.edit_mahasiswa')}}" class="card-link">Update Profil</a>
                            <a href="{{ url_for('rmahasiswa.logout_mahasiswa')}}" class="card-link">Logout</a>
                        </div>
                    </div>
                    {% else %}
                    <h1>Menu Lain</h1>
                    <li>Data Mahasiswa</li>
                    <li>Data Dosen</li>
                    {% endif %}

                    
                </div>
            </div>
        </div>

    </div>
    


</body>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"
    integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN"
    crossorigin="anonymous"></script>
<script src="{{ url_for('static',filename='js/bootstrap.min.js')}}"
    integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/"
    crossorigin="anonymous"></script>

</html>

sim/templates/data-mahasiswa.html
{% extends "base.html"%}

{% block konten%}

<h1>Daftar Akun</h1>
<form method="POST">
        {{form.hidden_tag()}}
    <div class="form-group">
        {{form.npm.label(class="form-control-label")}}
        {% if form.npm.errors %}
             {{form.npm(class="form-control is-invalid")}}

             <div class="invalid-feedback">
                 {%for error in form.npm.errors %}
                 <span>{{error}}</span>
                 {% endfor %}
             </div>
        {%else%}
            {{form.npm(class="form-control")}}
        
        {%endif%}
    </div>

    <div class="form-group">
        {{form.nama.label(class="form-control-label")}}
        {{form.nama(class="form-control")}}
    </div>

    <div class="form-group">
        {{form.email.label(class="form-control-label")}}
        {% if form.email.errors %}
        {{form.email(class="form-control is-invalid")}}

        <div class="invalid-feedback">
            {%for error in form.email.errors %}
            <span>{{error}}</span>
            {% endfor %}
        </div>
        {%else%}
            {{form.email(class="form-control")}}
        
        {%endif%}
    </div>

    <div class="form-group">
        {{form.kelas.label(class="form-control-label")}}
        {{form.kelas(class="form-control")}}
    </div>

    <div class="form-group">
        {{form.alamat.label(class="form-control-label")}}
        {{form.alamat(class="form-control")}}
    </div>
    
    <div class="form-group">
        {{form.password.label(class="form-control-label")}}
        {% if form.password.errors %}
             {{form.password(class="form-control is-invalid")}}

             <div class="invalid-feedback">
                 {%for error in form.password.errors %}
                 <span>{{error}}</span>
                 {% endfor %}
             </div>
        {%else%}
            {{form.password(class="form-control")}}
        
        {%endif%}
    </div>

    <div class="form-group">
        {{form.konf_pass.label(class="form-control-label")}}
        {% if form.konf_pass.errors %}
             {{form.konf_pass(class="form-control is-invalid")}}

             <div class="invalid-feedback">
                 {%for error in form.konf_pass.errors %}
                 <span>{{error}}</span>
                 {% endfor %}
             </div>
        {%else%}
            {{form.konf_pass(class="form-control")}}
        
        {%endif%}
    </div>
    <div class="form-group">
            {{form.submit(class="btn btn-primary")}}
    </div>
 
</form>


{% endblock%}

sim/templates/detail_pendataan.html
{% extends "base.html"%}

{% block konten%}

<h3>Detail Pendataan</h3>
<div class="alert alert-success" role="alert">
    <h4 class="alert-heading">Well done!</h4>


</div>

<div class="alert alert-warning" role="alert">
    <h4 class="alert-heading">Data Detail Pendataan</h4>


    <table class="table table-hover">
        <tr>
            <td>Subjek</td>
            <td>{{dt_pendataan.subjek}}</td>
        </tr>
        <tr>
            <td>Frekuensi</td>
            <td>{{dt_pendataan.frekuensi}}</td>
        </tr>
        <tr>
            <td>Detail :</td>
            <td>{{dt_pendataan.detail}}</td>
        </tr>

    </table>
</div>

<a class="btn btn-warning" href="{{url_for('rmahasiswa.pendataanto')}}">Kembali</a>

{% endblock%}

sim/templates/detail_pengaduan.html
{% extends "base.html"%}

{% block konten%}

<h3>Detail Pengaduan</h3>
<div class="alert alert-success" role="alert">
    <h4 class="alert-heading">Well done!</h4>


</div>

<div class="alert alert-warning" role="alert">
    <h4 class="alert-heading">Data Detail Pengaduan</h4>


    <table class="table table-hover">
        <tr>
            <td>Tgl Post</td>
            <td>{{dt_pengaduan.tgl_post}}</td>
        </tr>
        <tr>
            <td>Subjek</td>
            <td>{{dt_pengaduan.subjek}}</td>
        </tr>
        <tr>
            <td>Kategori</td>
            <td>{{dt_pengaduan.kategori}}</td>
        </tr>
        <tr>
            <td>Detail :</td>
            <td>{{dt_pengaduan.detail_pengaduan}}</td>
        </tr>

    </table>
</div>

<a class="btn btn-warning" href="{{url_for('rmahasiswa.pengaduan')}}">Kembali</a>

{% endblock%}

sim/templates/home.html
{% extends "base.html"%}

{% block konten%}

<div class="jumbotron">
    <h1 class="display-4">Welcome To My Website</h1>
    <p class="lead">Silahkan di lihat - lihat halaman home ini. Semoga suka ya!</p>
    <hr class="my-4">
    <p>Perkenalkan nama saya Riska Tawari salah satu mahasiswi dari Universitas Muhammadiyah Maluku Utara prodi Teknik
        Informatika semester IV. Di website ini saya hanya ingin memberitahu kepada teman-teman bahwa web ini merupakan web perdana 
        saya jadi mohon maaf jika masih banyak kekurangannya. Satu hal yang harus teman-teman ketahui "BERANILAH BERKARYA.KARENA UNTUK MENJADI KAYA KITA BUTUH KARYA BUKAN GAYA."
    </p>
    <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
</div>
{% endblock%}

sim/templates/login_mahasiswa.html
{% extends "base.html"%}

{% block konten%}

<h1>Daftar Akun</h1>
<form method="POST">
        {{form.hidden_tag()}}
    <div class="form-group">
        {{form.npm.label(class="form-control-label")}}
        {% if form.npm.errors %}
             {{form.npm(class="form-control is-invalid")}}

             <div class="invalid-feedback">
                 {%for error in form.npm.errors %}
                 <span>{{error}}</span>
                 {% endfor %}
             </div>
        {%else%}
            {{form.npm(class="form-control")}}
        
        {%endif%}
    </div>

    
    
    <div class="form-group">
        {{form.password.label(class="form-control-label")}}
        {% if form.password.errors %}
             {{form.password(class="form-control is-invalid")}}

             <div class="invalid-feedback">
                 {%for error in form.password.errors %}
                 <span>{{error}}</span>
                 {% endfor %}
             </div>
        {%else%}
            {{form.password(class="form-control")}}
        
        {%endif%}
    </div>

   
   
    <div class="form-group">
            {{form.submit(class="btn btn-primary")}}
    </div>
 
<span><a href="{{url_for('rmahasiswa.data_m')}}">Daftar Akun</a></span>

</form>


{% endblock%}

sim/templates/pendataan.html
{% extends "base.html"%}

{% block konten%}

<div class="jumbotron">
    <h3>AGENDA DAN INFORMASI</h3>
    <div class="alert alert-success" role="alert">
        <p>Hallo Teman-teman silahkan isi agenda maupun informasi yang ingin teman-teman tambahkan
            untuk keperluan kita selanjutnya di bawah ini.
        </p>
    </div>
    
    <div class="alert alert-success" role="alert">
    <!--form pengaduan-->
    <form method="POST">
        {{form.hidden_tag()}}
        <div class="form-group mb-3">
            {{form.subjek.label(class="form-control-label")}}
            {% if form.subjek.errors %}
            {{form.subjek(class="form-control is-invalid")}}

            <div class="invalid-feedback">
                {%for error in form.subjek.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </div>
            {%else%}
            {{form.subjek(class="form-control")}}

            {%endif%}
        </div>

        <div class="form-group mb-3">
            {{form.frekuensi.label(class="form-control-label")}}
            {% if form.frekuensi.errors %}
            {{form.frekuensi(class="form-control is-invalid")}}

            <div class="invalid-feedback">
                {%for error in form.frekuensi.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </div>
            {%else%}
            {{form.frekuensi(class="form-control")}}
            {%endif%}
        </div>

        <div class="form-group mb-3">
            {{form.detail.label(class="form-control-label")}}
            {% if form.detail.errors %}
            {{form.detail(class="form-control is-invalid")}}

            <div class="invalid-feedback">
                {%for error in form.detail.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </div>
            {%else%}
            {{form.detail(class="form-control")}}
            {%endif%}
        </div>

        <div class="form-group">
            {{form.submit(class="btn btn-primary")}}
        </div>
    </form>
</div>

    <hr class="my-4">
    <h4>Data Pengaduan</h4>

    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Subjek</th>
                    <th scope="col">Frekuensi</th>
                    <th scope="col">Detail</th>

                    <th scope="col">Edit</th>
                    <th scope="col">Hapus</th>
                </tr>
            </thead>
            <tbody>
                {% for data in dt_pendataan %}
                <tr>
                    <th scope="row">
                        <a href="{{url_for('rmahasiswa.detail_pendataan',ed_id=data.id)}}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                class="bi bi-arrow-up-right-circle-fill" viewBox="0 0 16 16">
                                <path
                                    d="M0 8a8 8 0 1 0 16 0A8 8 0 0 0 0 8zm5.904 2.803a.5.5 0 1 1-.707-.707L9.293 6H6.525a.5.5 0 1 1 0-1H10.5a.5.5 0 0 1 .5.5v3.975a.5.5 0 0 1-1 0V6.707l-4.096 4.096z" />
                            </svg>
                        </a>
                    </th>


                    <td>{{data.subjek}}</td>
                    <td>{{data.frekuensi}}</td>
                    <td>{{data.detail}}</td>

                    <td><a class="btn btn-secondary"
                            href="{{url_for('rmahasiswa.update_pendataan',ed_id=data.id)}}">Edit</a></td></button>
                    <td><a class="btn btn-info" href="/delete_pendataan/{{data.id}}" onclick="return confirm('yakin mau hapus?')">
                            Hapus</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <a class="btn btn-primary" href="{{url_for('rmahasiswa.pendataanto')}}">Kembali</a>
    </div>
</div>

{% endblock%}

sim/templates/pengaduan.html
{% extends "base.html"%}

{% block konten%}

<div class="jumbotron">

    <h3>Pengaduan</h3>
    <!--form pengaduan-->
    <form method="POST">
        {{form.hidden_tag()}}
        <div class="form-group">
            {{form.subjek.label(class="form-control-label")}}
            {% if form.subjek.errors %}
            {{form.subjek(class="form-control is-invalid")}}

            <div class="invalid-feedback">
                {%for error in form.subjek.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </div>
            {%else%}
            {{form.subjek(class="form-control")}}

            {%endif%}
        </div>

        <div class="form-group">
            {{form.kategori.label(class="form-control-label")}}
            {% if form.kategori.errors %}
            {{form.kategori(class="form-control is-invalid")}}

            <div class="invalid-feedback">
                {%for error in form.kategori.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </div>
            {%else%}
            {{form.kategori(class="form-control")}}
            {%endif%}
        </div>

        <div class="form-group">
            {{form.detail_pengaduan.label(class="form-control-label")}}
            {% if form.detail_pengaduan.errors %}
            {{form.detail_pengaduan(class="form-control is-invalid")}}

            <div class="invalid-feedback">
                {%for error in form.detail_pengaduan.errors %}
                <span>{{error}}</span>
                {% endfor %}
            </div>
            {%else%}
            {{form.detail_pengaduan(class="form-control")}}
            {%endif%}
        </div>

        <div class="form-group">
            {{form.submit(class="btn btn-primary")}}
        </div>
    </form>

    <hr class="my-4">
    <h4>Data Pengaduan</h4>

    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Tgl</th>
                    <th scope="col">Subjek</th>
                    <th scope="col">Kategori</th>

                    <th scope="col">Edit</th>
                    <th scope="col">Hapus</th>
                </tr>
            </thead>
            <tbody>
                {% for data in dt_pengaduan%}
                <tr>
                    <th scope="row">
                        <a href="{{url_for('rmahasiswa.detail_pengaduan',ed_id=data.id)}}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                class="bi bi-arrow-up-right-circle-fill" viewBox="0 0 16 16">
                                <path
                                    d="M0 8a8 8 0 1 0 16 0A8 8 0 0 0 0 8zm5.904 2.803a.5.5 0 1 1-.707-.707L9.293 6H6.525a.5.5 0 1 1 0-1H10.5a.5.5 0 0 1 .5.5v3.975a.5.5 0 0 1-1 0V6.707l-4.096 4.096z" />
                            </svg>
                        </a>
                    </th>


                    <td>{{data.tgl_post}}</td>
                    <td>{{data.subjek}}</td>
                    <td>{{data.kategori}}</td>

                    <td><a class="btn btn-secondary"
                            href="{{url_for('rmahasiswa.update_pengaduan',ed_id=data.id)}}">Edit</a></td></button>
                    <td><a class="btn btn-info" href="/delete/{{data.id}}" onclick="return confirm('yakin mau hapus?')">
                            Hapus</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock%}